### ISSUE TITLE
Don't use .eqv. when not needed

### ISSUE THREAD

**Issue by Beliavsky** [berkeoncel/FortranChessGame#2]
A line of code such as

`if (checkmate_status .eqv. .true.) exit`

can be written more simply as

`if (checkmate_status) exit`

**Comment by berkeoncel** [comment]
Thank you for your feedback. I have updated the code as per your suggestion:
`if (checkmate_status) exit`

The issue has been resolved, and the code is now more readable. Thanks again for your contribution!
